logging:
  level:
    dddhexagonal: debug
    root: info
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
endpoints:
  shutdown:
    enabled: true
  beans:
    enabled: true
