spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://127.0.0.1:5442/dddhexagonal?autoreconnect=true"
    username: "postgres"
    password: ""
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
  flyway:
    locations: classpath:db/migrations/postgres
    schemas: public,onboarding,user_management
logging:
  level:
    org.flywaydb.core: DEBUG
